core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = 'core'

urlpatterns = [

	# Login
	url(r'^login/$', views.login, name='login'),

	# Logout
	url(r'^logout/$', views.logout, name='logout'),
]

financial/urls.py
from django.conf.urls import url, include

from .views import *

# Application Routes (URLs)

app_name = 'financial'

urlpatterns = [
		# client costs
		url(r'^add-cost/(?P<pk>\d+)/$', AddClientCost.as_view(), name='add'),
		url(r'^remove-cost/(?P<pk>\d+)/$', DeleteClientCost.as_view(), name='delete'),
		url(r'^update-cost/(?P<pk>\d+)/$', UpdateClientCost.as_view(), name='update'),
		#company costs
		url(r'^add-company-cost/(?P<pk>\d+)/$', AddCompanyCost.as_view(), name='add_company_cost'),
		url(r'^remove-company-cost/(?P<pk>\d+)/$', DeleteCompanyCost.as_view(), name='delete_company_cost'),
		url(r'^update-company-cost/(?P<pk>\d+)/$', UpdateCompanyCost.as_view(), name='update_company_cost'),
		#cost details
		url(r'^cost/(?P<pk>\d+)/(?P<type>\w+)/$', CostView.as_view(), name='cost'),
		#estimted cost generator
		url(r'^estimate-cost/(?P<pk>\d+)/$', EstimatedCostGenerator.as_view(), name='estimate'),
		#CostTypes
		url(r'^add-type/(?P<pk>\d+)/$', AddCostType.as_view(), name='add_cost_type'),
		url(r'^update-type/(?P<pk>\d+)/$', UpdateCostType.as_view(), name='update_cost_type'),
		url(r'^delete-type/(?P<pk>\d+)/$', DeleteCostType.as_view(), name='delete_cost_type'),
		#services
		url(r'^add-service/(?P<pk>\d+)/$', AddService.as_view(), name='add_service'),
		url(r'^update-service/(?P<pk>\d+)/$', UpdateService.as_view(), name='update_service'),
		url(r'^delete-service/(?P<pk>\d+)/$', DeleteService.as_view(), name='delete_service'),
		#invoices
		url(r'^invoices/(?P<pk>\d+)/$', ManageInvoices.as_view(), name='invoice'),
		url(r'^invoice-items/(?P<pk>\d+)/(?P<id>\w+)/$', InvoiceDetails.as_view(), name='invoice_items'),
		url(r'^create-invoice/$', AddInvoice.as_view(), name='create_invoice'),
		url(r'^update-invoice/$', UpdateInvoice.as_view(), name='update_invoice'),
]

management/urls.py
from django.conf.urls import url, include

from .views import *

# Application Routes (URLs)

app_name = 'management'

urlpatterns = [
    	# client urls
		url(r'^add-client/(?P<pk>\d+)/$', AddClient.as_view(), name='add_client'),
		url(r'^delete-client/(?P<pk>\d+)/$', DeleteClient.as_view(), name='delete_client'),
		url(r'^update-client/(?P<pk>\d+)/$', UpdateClient.as_view(), name='update_client'),
		url(r'^detail-client/(?P<pk>\d+)/$', DetailClient.as_view(), name='detail_client'),
		# project urls
		url(r'^add-project/(?P<pk>\d+)/$', AddProject.as_view(), name='add_project'),
		url(r'^delete-project/(?P<pk>\d+)/$', DeleteProject.as_view(), name='delete_project'),
		url(r'^update-project/(?P<pk>\d+)/(?P<pk2>\d+)$', UpdateProject.as_view(), name='update_project'),
		# company mangement
		url(r'^company-page/(?P<pk>\d+)/$', CompanyPage.as_view(), name='company_page'),
		url(r'^add-company/$', AddCompany.as_view(), name='add_company'),
		url(r'^edit-company/(?P<pk>\d+)/$', UpdateCompany.as_view(), name='edit_company'),
		url(r'^delete-company/(?P<pk>\d+)/$', DeleteCompany.as_view(), name='delete_company'),
		# member views
		url(r'^add-new-member/(?P<pk>\d+)/$', AddNewMember.as_view(), name='add_new_member'),
		url(r'^add-member/(?P<company>\d+)/(?P<user>\d+)/$', UpdateCompanyMembers.as_view(), name='add_member'),
	]

website/urls.py
from django.conf.urls import url, include

from .views import HomePageView, NewUser

# Application Routes (URLs)

app_name = 'website'

urlpatterns = [
    	# General Page Views
		url(r'^$', HomePageView.as_view(), name='homepage_view'),
		url(r'^register/$', NewUser.as_view(), name='register'),
]

website/models.py
from django.db import models

website/forms.py
from django import forms

website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
import json
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from management.forms import MemberForm
from management.models import Company
from financial.models import Cost

#-------------------------------------------------------------------------------
# Page Views
#-------------------------------------------------------------------------------
class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'website/homepage.html'

    def get_context_data(self, *args, **kwargs):
        user = User.objects.get(pk=self.request.user.pk)
        companies = Company.objects.filter(members__in=[self.request.user])
        context = { 'companies': companies }
        return context

class NewUser(CreateView):
    form_class = MemberForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('core:login')

website/templates/website/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">


		<title>{% block title %}Web Client Management{% endblock title %}</title>

		<!-- CSS -->
			<!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
			<link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
			<link rel="stylesheet" href="{% static 'website/css/animate.css' %}"/>
			<link rel="stylesheet" href="{% static 'website/css/style.css' %}"/>
			{% block custom_css %}
			{% endblock custom_css %}

		<!-- JavaScript -->

			<!-- jQuery library -->
			<script src="{% static 'website/js/jquery.min.js' %}"></script>

			<!-- Popper JS -->
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

			<!-- Latest compiled JavaScript -->
			<script src="{% static 'website/js/bootstrap.min.js' %}"></script>
			{% include 'website/js/functions.html' %}
			<script src="{% static 'website/js/main.js' %}"></script>

			{% block head_js %}
			{% endblock head_js %}

	</head>
	<body>

		{% include 'website/navbar.html' %}

		{% block content %}
		{% endblock content %}

		{% block js %}
		{% endblock js %}
	</body>
</html>

website/templates/website/homepage.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style>
  .fa-plus {
    color: var(--primary-color) !important;
  }

#myInput {
  border-radius: 10px;
  border-color: var(--secondary-color) !important;
  outline: none;
}
.btn {
  width: 100%;
  background-color: var(--primary-color) !important;
}
.fa-edit {
    color: var(--primary-color) !important;
}
.fa-plus {
  color: var(--primary-color) !important;
  margin-top: 5px;
}
thead {
  background-color: var(--secondary-color) !important;
  color: white;
}
th {
  border-top-right-radius: 10px;
  border-top-left-radius: 10px;
}
.label {
  font-weight: bold;
}
.heading {
  text-align: center;
}
.title {
  background-color: var(--secondary-color) !important;
  color: white;
  text-align: center;

  border-radius: 10px;
  padding: 10px;
  padding-bottom: 15px;

}
.company-select {
  width: 90%;
  margin-right: 10px;
}
</style>
{% endblock custom_css %}

{% block content %}
<div style="max-width: 50%;" class="container">
  <div class="row">
    <div class="col">
      <br><br>
      <h1 class="title">Welcome to Company Management</h1><br/><br/>
    </div>
  </div>
  <div class="row">
    {% if companies %}
    <div class="col">
      <table class="table">
        <thead>
        <tr><th colspan="2">
        <h3 style="text-align: center;">Please select a company below</h3>
        </thead>
        <tbody>
          <tr><td>
      <select class="company-select" id="company">
        <option>-----------------</option>
        {% for company in companies %}
        <option id="company-{{ company.pk }}" href="{% url 'management:company_page' company.pk %}" value="{{ company.pk }}">{{ company }}</option>
        {% endfor %}
      </select>
    </td>
    <td>
      <h3 class="fa fa-plus" id="add" href="{% url 'management:add_company' %}"></h3>
        </td>
      </tr>
      </tbody>
      </table>
      <button class="btn btn-success" id="manage">Manage Company</button>
    </div>
    {% else %}
    <div class="col">
      <table class="table">
        <thead>
        <tr><th>
        <h3 style="text-align: center;">You are not part of any companies!</h3>
        </thead>
        <tbody>
          <tr><td>
            <button class="btn btn-success" id="add" href="{% url 'management:add_company' %}">Add a new company</button></td>
      </tbody>
      </table>
    {% endif %}
    </div>
  </div>
{% include 'website/server_messages.html' %}

        {% endblock content %}

{% block js %}
<script>
  $('#manage').click(function() {
    var id = $('#company').val();
    window.location.href = $('#company-' + id).attr("href");
  })
  $('#add').click(function() {
    window.location.href = $(this).attr('href');
  });

</script>
{% endblock js %}

website/templates/website/homepage1.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style>
  .fa-plus {
    color: var(--primary-color) !important;
  }

#myInput {
  border-radius: 10px;
  border-color: var(--secondary-color) !important;
  outline: none;
}
.btn {
  width: 100%;
  background-color: var(--primary-color) !important;
}
.fa-edit {
    color: var(--primary-color) !important;
}
.fa-plus {
  color: var(--primary-color) !important;
}
thead {
  background-color: var(--secondary-color) !important;
  color: white;
}
th {
  border-top-right-radius: 10px;
  border-top-left-radius: 10px;
}
.label {
  font-weight: bold;
}
.heading {
  text-align: center;
}
.title {
  background-color: var(--secondary-color) !important;
  color: white;

  border-radius: 10px;
  padding: 10px;
  padding-bottom: 15px;

}
</style>
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}

<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1 class="title">Tech and Mech Client Management</h1><br/>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 text-center">

      <table class="table">
        <thead>
          <tr>
            <th colspan="2" class="heading">
              <h2>
          Clients
          <i class="fas fa-plus" href="{% url 'management:add_client' %}"></i><br/>
          </h2>
          <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for clients.." title="Type in a client">
          </th>
          </tr>
          </thead>
          <tbody id="client-table">
        {% for client in clients %}
        <tr id="row-{{ client.pk }}" ><td class="client" href="{% url 'management:detail_client' client.pk %}"><h5>{{ client.name }}</h5></td>
        <td><i id="{{ client.pk }}" style="color:red" class="fas fa-trash-alt" href="{% url 'management:delete_client' client.pk %}"></i></tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="col text-center">
      <table class="table">
        <thead>
        <tr><th class="heading" colspan="2">
        <h2>Income Summary </h2>
        </th></tr>
        </thead>
        <tbody>

        <tr><th class="cost" href="{% url 'financial:list' 'elementor' %}">Elementor:</th>
          {% if elementor %}
          <td class="value"s>${{ elementor }}</td>
          {% else %}
          <td>$0</td>
          {% endif %}
        <tr><th class="cost" href="{% url 'financial:list' 'domains' %}">Domains:</th>
          {% if domains %}
          <td class="value" value="{{ domains }}">${{ domains }}</td>
          {% else %}
          <td>$0</td>
          {% endif %}
        <tr><th class="cost" href="{% url 'financial:list' 'server_hosting' %}">Servers:</th>
          {% if servers %}
          <td class="value" value="{{ servers }}">${{ servers }}</td>
          {% else %}
          <td>$0</td>
          {% endif %}
        <tr><th class="cost" href="{% url 'financial:list' 'project' %}">Projects:</th>
          {% if project %}
          <td class="value" value="{{ project }}">${{ project }}</td>
          {% else %}
          <td>$0</td>
          {% endif %}
          <tr style="border-top: 1px solid black;">
            <th>
              Total:
            </th>
            <td class="value">${{ total }}
              </td>
              </tr>
        </tbody>
        </table>
    </div>
</div>

        {% endblock content %}

{% block js %}
<script>

//------------------------------------------------------

  $('.fa-plus').click(function() {
    window.location.href = $(this).attr('href');
    })

</script>
{% endblock js %}

website/templates/website/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">
    <img id="logo" src="{% static 'website/images/logo.jpg' %}" alt="Logo" style="width:40px;">
  </a>
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      {% if company %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Switch Companies
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for company in companies %}
            <a class="dropdown-item" href="{% url 'management:company_page' company.pk %}">{{ company }}</a>
          {% endfor %}
        </div>
      </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'financial:estimate' company.pk %}">Estimated Cost Generator</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
    </li>
  </ul>
</nav>

website/templates/website/server_messages.html
<!-- Server Messages to User -->
<div class="row">
  {% block custom_message %} {% endblock custom_message %}
  <div class="col center">
    {% if messages %}
        {% for message in messages %}
            {% if "error" in message.level_tag %}
            <div class="alert alert-warning">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% else %}
            <div class="alert alert-success">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <br />
    {% endif %}
  </div>
</div>