core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = 'core'

urlpatterns = [

	# Login
	url(r'^login/$', views.login, name='login'),

	# Logout
	url(r'^logout/$', views.logout, name='logout'),
]

financial/urls.py
from django.conf.urls import url, include

from .views import *

# Application Routes (URLs)

app_name = 'financial'

urlpatterns = [
		# client costs
		url(r'^add-cost/(?P<pk>\d+)/$', AddClientCost.as_view(), name='add'),
		url(r'^remove-cost/(?P<pk>\d+)/$', DeleteClientCost.as_view(), name='delete'),
		url(r'^update-cost/(?P<pk>\d+)/$', UpdateClientCost.as_view(), name='update'),
		#company costs
		url(r'^add-company-cost/(?P<pk>\d+)/$', AddCompanyCost.as_view(), name='add_company_cost'),
		url(r'^remove-company-cost/(?P<pk>\d+)/$', DeleteCompanyCost.as_view(), name='delete_company_cost'),
		url(r'^update-company-cost/(?P<pk>\d+)/$', UpdateCompanyCost.as_view(), name='update_company_cost'),
		#cost details
		url(r'^cost/(?P<pk>\d+)/(?P<type>\w+)/$', CostView.as_view(), name='cost'),
		#estimted cost generator
		url(r'^estimate-cost/(?P<pk>\d+)/$', EstimatedCostGenerator.as_view(), name='estimate'),
		#CostTypes
		url(r'^add-type/(?P<pk>\d+)/$', AddCostType.as_view(), name='add_cost_type'),
		url(r'^update-type/(?P<pk>\d+)/$', UpdateCostType.as_view(), name='update_cost_type'),
		url(r'^delete-type/(?P<pk>\d+)/$', DeleteCostType.as_view(), name='delete_cost_type'),
		#services
		url(r'^add-service/(?P<pk>\d+)/$', AddService.as_view(), name='add_service'),
		url(r'^update-service/(?P<pk>\d+)/$', UpdateService.as_view(), name='update_service'),
		url(r'^delete-service/(?P<pk>\d+)/$', DeleteService.as_view(), name='delete_service'),
		#invoices
		url(r'^invoices/(?P<pk>\d+)/$', ManageInvoices.as_view(), name='invoice'),
		url(r'^invoice-items/(?P<pk>\d+)/(?P<id>\w+)/$', InvoiceDetails.as_view(), name='invoice_items'),
		url(r'^create-invoice/$', AddInvoice.as_view(), name='create_invoice'),
		url(r'^update-invoice/$', UpdateInvoice.as_view(), name='update_invoice'),
]

management/urls.py
from django.conf.urls import url, include

from .views import *

# Application Routes (URLs)

app_name = 'management'

urlpatterns = [
    	# client urls
		url(r'^add-client/(?P<pk>\d+)/$', AddClient.as_view(), name='add_client'),
		url(r'^delete-client/(?P<pk>\d+)/$', DeleteClient.as_view(), name='delete_client'),
		url(r'^update-client/(?P<pk>\d+)/$', UpdateClient.as_view(), name='update_client'),
		url(r'^detail-client/(?P<pk>\d+)/$', DetailClient.as_view(), name='detail_client'),
		# project urls
		url(r'^add-project/(?P<pk>\d+)/$', AddProject.as_view(), name='add_project'),
		url(r'^delete-project/(?P<pk>\d+)/$', DeleteProject.as_view(), name='delete_project'),
		url(r'^update-project/(?P<pk>\d+)/(?P<pk2>\d+)$', UpdateProject.as_view(), name='update_project'),
		# company mangement
		url(r'^company-page/(?P<pk>\d+)/$', CompanyPage.as_view(), name='company_page'),
		url(r'^add-company/$', AddCompany.as_view(), name='add_company'),
		url(r'^edit-company/(?P<pk>\d+)/$', UpdateCompany.as_view(), name='edit_company'),
		url(r'^delete-company/(?P<pk>\d+)/$', DeleteCompany.as_view(), name='delete_company'),
		# member views
		url(r'^add-new-member/(?P<pk>\d+)/$', AddNewMember.as_view(), name='add_new_member'),
		url(r'^add-member/(?P<company>\d+)/(?P<user>\d+)/$', UpdateCompanyMembers.as_view(), name='add_member'),
	]

Management/models.py
from django.db import models
from django.urls import reverse
from datetime import timedelta
from financial.models import ClientCost, CompanyCost, CostType
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=200, unique=True)
    members = models.ManyToManyField(User)
    stripe_secret = models.CharField(max_length=200, blank=True, null=True)
    stripe_public = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('management:company_page', kwargs={'pk':self.pk})

    def get_project_income(self):
        amount = 0
        for client in Client.objects.filter(company=self):
            amount += sum(project.amount for project in Project.objects.filter(client=client))
        return amount

    def get_client_costs(self, type):
        costs = []
        for client in Client.objects.filter(company=self):
            for cost in ClientCost.objects.filter(client=client):
                costs.append(cost)
        return costs


class Client(models.Model):
    name = models.CharField(max_length=100, unique=True)
    company = models.ForeignKey(Company, default=None,  on_delete=models.CASCADE)
    customer_id = models.CharField(max_length=100, blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(blank=True, null=True)
    folder_link = models.URLField(blank=True, null=True, unique=True)
    additional_information = models.TextField(blank=True, null=True)
    amount_owed = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('management:company_page', kwargs={'pk': self.company.pk})

    def get_cost(self, pk):
        type = CostType.objects.filter(pk=pk)
        if Cost.objects.filter(client=self, type=type).exists():
            cost = Cost.objects.get(client=self, type=type)
            return cost
        else:
            return None

    def get_profit(self, type):
        try:
            cost = Cost.objects.get(client=self, type=type)
        except:
            pass
        return cost.get_total_cost()

    def get_amount_owed(self):
        total = sum(cost.amount for cost in ClientCost.objects.filter(client=self))
        return total

    def get_customer_id(self):
        return self.customer_id


class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    github_link = models.URLField(blank=True, null=True, unique=True)
    folder_link = models.URLField(blank=True, null=True, unique=True)

    def __str__(self):
        return str(self.name)

financial/models.py
from django.db import models
from django.urls import reverse
from enum import Enum
from datetime import timedelta
import stripe

# Create your models here.

class Service(models.Model):
    class Meta:
        unique_together = (('name', 'company'), )

    name = models.CharField(max_length=100, unique="True")
    company = models.ForeignKey('management.Company', on_delete=models.CASCADE)
    cost_per_hour = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('management:company_page', kwargs={'pk': self.company.pk})

class CostType(models.Model):
    class Meta:
        unique_together = (('name', 'company'), )

    ONE_TIME = 'ot'
    BIWEEKLY = 'wk'
    MONTHLY = 'mo'
    ANNUALY = 'an'

    PAYMENT_PEROID = (
        (ONE_TIME, 'One Time'),
        (BIWEEKLY, 'Bi-weekly'),
        (MONTHLY, 'Monthly'),
        (ANNUALY, 'Annualy')
    )

    name = models.CharField(max_length=100)
    company = models.ForeignKey('management.Company', on_delete=models.CASCADE)
    payment_period = models.CharField(max_length=2, choices=PAYMENT_PEROID, default=ONE_TIME)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('management:company_page', kwargs={'pk': self.company.pk})

class Cost(models.Model):
    class Meta:
        abstract = True

    type = models.ForeignKey(CostType, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    last_payment_date = models.DateTimeField(auto_now=True)

    def get_next_payment(self):
        if self.type.payment_period == 'wk':
            next_payment = self.last_payment_date + timedelta(days=14)
        elif self.type.payment_period == 'mo':
            next_payment = self.last_payment_date + timedelta(weeks=4)
        elif self.type.payment_period == 'an':
            next_payment = self.last_payment_date + timedelta(weeks=52)
        else:
            next_pamyent = self.last_payment_date
        return next_payment

class ClientCost(Cost):
    client = models.ForeignKey('management.Client', on_delete=models.CASCADE)
    project = models.ForeignKey('management.Project', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.client) + ' | ' + self.type

class CompanyCost(Cost):
    company = models.ForeignKey('management.Company', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.company) + ' | ' + self.type

    def get_absolute_url(self):
        return reverse('management:company_page', kwargs={'pk':self.company.pk})

Management/forms.py
from django import forms
from .models import Project, Client, Company
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['amount']
        widgets = {'client': forms.HiddenInput()}

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['customer_id']
        widgets = {
        'company': forms.HiddenInput(),
        }

class MemberForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'members',)
        widgets = {'members': forms.MultipleHiddenInput()}

Management/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, FormView, DeleteView
from .models import Client, Project, Company
from financial.models import ClientCost, CompanyCost, Service, CostType
from .mixins import DeleteViewAjax
from .forms import ProjectForm, ClientForm, MemberForm, CompanyForm
from .utils import get_income_cost, get_total
from financial.utils import get_invoices

# client views
class AddClient(LoginRequiredMixin, CreateView):
    form_class = ClientForm
    template_name = 'management/client_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Client'
        context['next'] = reverse('management:company_page', kwargs={'pk': self.kwargs.get('pk')})
        return context

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(*args, **kwargs)
        company = Company.objects.get(pk=self.kwargs.get('pk'))
        initial['company'] = company
        return initial

class DeleteClient(LoginRequiredMixin, DeleteViewAjax):
    model = Client

class UpdateClient(LoginRequiredMixin, UpdateView):
    model = Client
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Client'
        return context

class DetailClient(LoginRequiredMixin, DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.filter(client=self.object)
        context['client_costs'] = ClientCost.objects.filter(client=self.object)
        return context

# member views
class AddNewMember(LoginRequiredMixin, FormView):
    form_class = MemberForm
    template_name = 'management/member_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = reverse('management:company_page', kwargs={'pk':
                                                        self.kwargs.get('pk')})
        return context

    def form_valid(self, form, **kwargs):
        try:
            self.object = form.save()
            company = Company.objects.get(pk=self.kwargs.get('pk'))
            company.members.add(self.object)
            company.save()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(self.get_success_url())



    def get_success_url(self, **kwargs):
        next = self.request.POST.get('next', reverse('website:homepage_view'))
        return next


# project views
class AddProject(LoginRequiredMixin, CreateView):
    template_name = 'management/project_form.html'
    form_class = ProjectForm

    def get_initial(self, **kwargs):
        initial = super(AddProject, self).get_initial()
        try:
            initial['client'] = Client.objects.get(pk=self.kwargs.get('pk'))
        except Exception as e:
            print(e)
        return initial

    def get_context_data(self, **kwargs):
        context = super(AddProject, self).get_context_data(**kwargs)
        context['title'] = 'Add Project'
        context['next'] = reverse('management:detail_client', kwargs={'pk':self.kwargs.get('pk')})
        return context


    def get_success_url(self, **kwargs):
        print(self.request.POST.get('next'))
        next = self.request.POST.get('next', reverse('website:homepage_view'))
        print(next)
        return next

class DeleteProject(LoginRequiredMixin, DeleteViewAjax):
    model = Project

class UpdateProject(LoginRequiredMixin, UpdateView):
    model = Project
    template_name = 'management/project_form.html'
    form_class = ProjectForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Project'
        context['next'] =  reverse('management:detail_client', kwargs={'pk': self.kwargs.get('pk2')})
        return context

    def get_success_url(self, **kwargs):
        next = self.request.POST.get('next', reverse('website:homepage_view'))
        return next

#company Management
class CompanyPage(LoginRequiredMixin, TemplateView):
    template_name = 'management/company_page.html'

    def get_context_data(self, *args, **kwargs):
        company = Company.objects.get(pk=self.kwargs.get('pk'))
        self.request.session['company'] = company.pk
        if company.stripe_secret:
            key = company.stripe_secret
            invoices = get_invoices(key)
        else:
            invoices = []
        context = {
            'company': company,
            'clients': Client.objects.filter(company=company),
            'members': company.members.all(),
            'costs': CompanyCost.objects.filter(company=company),
            'types': CostType.objects.filter(company=company),
            'total': get_total(company),
            'services': Service.objects.filter(company=company),
            'invoices' : invoices

        }
        return context


class AddCompany(LoginRequiredMixin, CreateView):
    form_class = CompanyForm
    template_name = 'management/company_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Company'
        return context

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(*args, **kwargs)
        initial['members'] = [self.request.user]
        return initial

class DeleteCompany(LoginRequiredMixin, DeleteViewAjax):
    model = Company

class UpdateCompany(LoginRequiredMixin, UpdateView):
    model = Company
    fields = ('name', 'stripe_secret', 'stripe_public')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Company'
        return context

class UpdateCompanyMembers(LoginRequiredMixin, View):
    def get(self, *args,**kwargs):
        company = Company.objects.get(pk=self.kwargs.get('company'))
        current_members = company.members.all()
        print(current_members)
        potential_members = User.objects.exclude(id__in=current_members.values_list('id', flat=True))
        print(potential_members)
        context = {
            'company': company,
            'users': User.objects.exclude(id__in=current_members.values_list('id', flat=True)),
        }
        return render(self.request, 'management/add_members.html', context)

    def post(self, *args, **kwargs):
        try:
            user = User.objects.get(pk=self.kwargs.get('user'))
            company = Company.objects.get(pk=self.kwargs.get('company'))
            company.members.add(user)
            company.save()
            success = True
            message = "Member added successfully"
        except Exception as e:
            success = False
            message = "Error adding memeber" + str(e)
        return JsonResponse({'success':success, 'message': message})

Management/templates/management/add_members.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style type="text/css">
  .btn {
    width: 100%;
    background-color: var(--primary-color) !important;
  }
  .fa-edit {
      color: var(--primary-color) !important;
  }
  .fa-plus {
    color: var(--primary-color) !important;
  }
  thead {
    background-color: var(--secondary-color) !important;
    color: white;
  }
  th {
    border-top-right-radius: 10px;
    border-top-left-radius: 10px;
  }
  .label {
    font-weight: bold;
  }
  .heading {
    text-align: center;
  }
</style>
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}
<div class="container">
<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table"> {% csrf_token %}
      <thead>
        <tr>
          <th colspan="2" class="heading">
            <h2>Select Memebers
              <i class="fa fa-plus" id="new" href="{% url 'management:add_new_member' company.pk %}"</h2>
          </th>
        </tr>
      </thead>
      <tbody class="user-table">
        <tr><th>User</th>
            <th>Add?</th>
        </tr>

        {% for user in users %}
        <tr id="row-{{ user.pk }}">
          <td>
            <h3>{{ user.first_name }} {{ user.last_name }}</h3?
          </td>
          <td>
            <h3><i class="fa fa-plus add"  id="{{ user.pk }}" href="{% url 'management:add_member' company.pk user.pk %}"></i>
              </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}


{% block js %}
<script>
$('.add').click(function(e) {
	setup_ajax();
	e.preventDefault();
	$.ajax({ // create an AJAX call...
			url: $(this).attr('href'), // the file to call
			type: 'POST', // GET or POST
			data: {  'csrfmiddlewaretoken': '{{ csrf_token }}' } , // get the form data
			success: function(response) { // on success..
				if(response.success) {
          location.reload();
				}
				else {
					alert(response.message)
				}
			}
	});
});

$('#new').click(function() {
  window.location.href= $(this).attr('href');
})
</script>
{% endblock js %}

Management/templates/management/client_form.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style type="text/css">
  .btn {
    width: 100%;
    background-color: var(--primary-color) !important;
  }
  .fa-edit {
      color: var(--primary-color) !important;
  }
  .fa-plus {
    color: var(--primary-color) !important;
  }
  thead {
    background-color: var(--secondary-color) !important;
    color: white;
  }
  th {
    border-top-right-radius: 10px;
    border-top-left-radius: 10px;
  }
  .label {
    font-weight: bold;
  }
  .heading {
    text-align: center;
  }
</style>
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}
<div class="container">
  <form method="POST">{% csrf_token %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table">
      <thead>
        <tr>
          <th colspan="2" class="heading">
            <h2>{{ title }}</h2>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
                  {{ form.as_table }}
                  <br/>

          </td>
        </tr>
      </tbody>
    </table>
      <input name="next" type="hidden" value="{{ next }}"></input>

      <button class="btn btn-success" type="submit">Save</button>
    </form>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
</script>
{% endblock js %}

Management/templates/management/company_page.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style>
  .fa-plus {
    color: var(--primary-color) !important;
  }

#myInput {
  width: 90%;
  border-radius: 10px;
  border-color: var(--secondary-color) !important;
  outline: none;
}
.btn {
  width: 100%;
  background-color: var(--primary-color) !important;
}
.fa-edit {
    color: var(--primary-color) !important;
}
.fa-plus {
  color: var(--primary-color) !important;
}
thead {
  background-color: var(--secondary-color) !important;
  color: white;
}
th {
  border-top-right-radius: 10px;
  border-top-left-radius: 10px;
}
.label {
  font-weight: bold;
}
.heading {
  text-align: center;
}
.title {
  background-color: var(--secondary-color) !important;
  color: white;
  text-align: center;

  border-radius: 10px;
  padding: 10px;
  padding-bottom: 15px;

}
.nav {
  display: inline;
}
.value {
  /* float: right; */
}
.table {
  display: table;
}
  </style>
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}
  {% load app_tags %}
<div class="container">
  <div class="row">
    <div class="col">
      <h2 style="text-align: center;">{{ company }} Homepage
        <i class="far fa-edit" id="edit-company" href="{% url 'management:edit_company' company.pk %}"></i>
      </h2>
      <br/>
      <div class="row">
        <div class="col">
      </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">

      <table class="table">
        <thead>
          <tr>
            <th colspan="2" class="heading">
              <h2>
          Clients
          <i class="fas fa-plus" href="{% url 'management:add_client' company.pk %}"></i><br/>
          </h2>
          <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for clients.." title="Type in a client">
          </th>
          </tr>
          </thead>
          <tbody id="client-table">
        {% for client in clients %}
        <tr id="row-{{ client.pk }}" ><td class="client" href="{% url 'management:detail_client' client.pk %}"><h5>{{ client.name }}</h5></td>
        <td><i id="{{ client.pk }}" style="color:red" class="fas fa-trash-alt delete-client" href="{% url 'management:delete_client' client.pk %}"></i></tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
  </div>
  <div class="row">
      <div class="col">
      <table class="table">
        <thead>
            <tr><th colspan="3" class="text-center"><h2>Income Summary
              <i class='fa fa-plus' href="{% url 'financial:add_cost_type' company.pk %}"></i>
              </h2>
              </th>
            </tr>
            <tr>
              <td><strong>Filter by:</strong></td>
              <td id="monthly">Monthly</td>
              <td id="yearly">Yearly</td>
            </tr>
        </thead>
        <tbody>
            {% for type in types %}
              <tr><th class="cost" href="{% url 'financial:cost' company.pk type.pk %}">{{ type.name }}:</th>
                <td class="value">${% get_income type company %}</td>
              </tr>
            {% endfor %}
            <tr><th>Projects:</th>
                <td class="value">${{ company.get_project_income }}</td>
            </tr>
            <tr style="border-top: 1px solid black;">
              <th>
                Total:
              </th>
              <td colspan="2" class="value">${{ total }}
                </td>
                </tr>
          </tbody>
      </table>
      </div>
    <div class="col">
      <table id="cost-table" class="table">
        <thead>
          <tr>
            <th colspan="5" class="heading">
              <h2 id="type">
                Open Invoices
                <i class='fa fa-plus' href="{% url 'financial:create_invoice' %}"></i>
              </h2>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>Client</th>
            <th>Charge</th>
            <th>Due Date</th>
            <th>Details</th>
          </tr>
              {% for invoice in invoices %}
              <tr>
                <td>{% get_customer invoice.customer %}</td>
                <td>${% get_amount invoice.amount_remaining %}</td>
                <td>{% get_date invoice.due_date %}</td>
              <td>
                <i class="fas fa-info" id="info" href="{% url 'financial:invoice_items' company.pk invoice.id %}"></i>
                </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
    </div>
  </div>
    <div class="row">
      <div class="col">
        <table id="member-table" class="table">
          <thead>
            <tr>
              <th colspan="2" class="heading">
                <h2 id="member">
                  Members
                  <i class='fa fa-plus' href="{% url 'management:add_member' company.pk 0 %}"></i>
                  </h2>
                </th>
              </tr>
            </thead>
          <tbody>
            {% for member in members %}
              <tr><td><h5 style="text-align: center;">{{ member.first_name }} {{ member.last_name }}</h5></td>
                <td><i class="fa fa-trash-alt" href=""></i></td>
              </tr>
            {% endfor %}

            </tbody>
            </table>
            </div>
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th colspan="4" class="heading">
              <h2 id="type">
                Services
                <i class='fa fa-plus' href="{% url 'financial:add_service' pk=company.pk %}"></i>
              </h2>
            </th>
          </tr>
        </thead>
        <tbody id="service-table">
          <tr>
            <th>Service</th>
            <th>Hourly Rate</th>
            <th>Edit</th>
          </tr>
          {% for service in services %}
            <tr id="row-{{ service.pk }}">
              <td>{{ service.name }}</td>
              <td>{{ service.cost_per_hour }}</td>
              <td><i class="fas fa-edit" href="{% url 'financial:update_service' service.pk %}"></i>
              <i id="{{ service.pk }}" class="fas fa-trash-alt delete-service" href="{% url 'financial:delete_service' service.pk %}"></i></td>
            </tr>
          {% endfor %}
          </tbody>
      </table>
    </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
//------------------------------------------------------
$('.fa-plus').click(function() {
  window.location.href = $(this).attr("href");
});
$('.fa-edit').click(function() {
  window.location.href = $(this).attr("href");
});
$('#monthly').click(function() {
  alert("Feature coming soon");
});
$('#yearly').click(function() {
  alert("Feature coming soon");
});

$(document).ready(function() {
  $('.value').each(function(){
    if(parseInt($(this).html().substring(1)) >= 0 ) {
        $(this).css("color","green");
    }
    else {
      $(this).css("color","red");
    }
  });
});
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#client-table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});



$('.delete-client').click(function() {
  var id = $(this).attr('id');
  if(confirm("Are you sure you want to delete this client?")) {
    $.get($(this).attr('href'), {}, function(data) {
      if(data.deleted) {
        $('#client-table #row-' + id).remove();
      }
      else {
        console.log("Could not delete client at this time!");
      }
    });
  }
});

$('.delete-service').click(function() {
  var id = $(this).attr('id');
  if(confirm("Are you sure you want to delete this service?")) {
    $.get($(this).attr('href'), {}, function(data) {
      if(data.deleted) {
        console.log(data.deleted);
        $('#service-table #row-' + id).remove();
      }
      else {
        console.log("Could not delete service at this time!");
      }
    });
  }
});

$('.client').click(function() {
  window.location.href = $(this).attr('href');
});

$('.cost').click(function() {
  window.location.href = $(this).attr('href')
})

</script>
{% endblock js %}